# Generated by Django 2.2 on 2019-04-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelist',
            old_name='badge_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='panelist',
            name='returning',
            field=models.BooleanField(default=False),
        ),
    ]
