# Generated by Django 2.2.3 on 2019-07-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20190407_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('conference', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=280, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
