# Generated by Django 2.2.3 on 2019-07-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_textblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Internal notes for conference staff about the submission.', null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='status',
            field=models.CharField(choices=[('yes', 'Accepted'), ('no', 'Rejected'), ('pen', 'Pending')], default='pen', max_length=3),
        ),
    ]
