# Generated by Django 2.2.3 on 2019-07-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20190718_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='status',
            field=models.CharField(choices=[('yes', 'Invited'), ('no', 'Not Invited'), ('pen', 'Pending')], default='pen', max_length=3),
        ),
    ]
