# Generated by Django 2.2.3 on 2019-07-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_panelist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Internal notes for conference staff about the panelist.', null=True),
        ),
    ]
