# Generated by Django 2.2.4 on 2019-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_panelist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='status',
            field=models.CharField(choices=[('yes', 'Invited'), ('no', 'Not Invited'), ('pen', 'Pending'), ('w', 'Withdrew')], default='pen', max_length=3),
        ),
    ]
