# Generated by Django 2.2.4 on 2021-12-01 09:14

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20191109_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=280)),
                ('panelist_form_open', models.BooleanField(default=False)),
                ('panel_form_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='panel',
            name='con_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='Panels',
                to='submissions.Conference'),
        ),
        migrations.AddField(
            model_name='panelist',
            name='con_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='Panelists',
                to='submissions.Conference'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='con_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='Textblocks',
                to='submissions.Conference'),
        ),
    ]
