# Generated by Django 2.2.4 on 2021-12-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_conf_slug_to_fk_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='conference',
        ),
    ]
