# Generated by Django 2.2.4 on 2021-12-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_auto_20211201_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='conference',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='Panels', to='submissions.Conference'),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='conference',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='Panelists', to='submissions.Conference'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='conference',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='Textblocks', to='submissions.Conference'),
        ),
    ]
