# Generated by Django 2.0 on 2018-02-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=280, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('av_required', models.BooleanField()),
                ('experience_required', models.BooleanField(default=False)),
                ('pro_track', models.BooleanField(default=False)),
                ('experience', models.ManyToManyField(blank=True, to='scheduler.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=280)),
                ('pronouns', models.CharField(max_length=280)),
                ('a11y', models.TextField(blank=True)),
                ('person_of_color', models.BooleanField(default=False)),
                ('man', models.BooleanField(default=False)),
                ('sched_sent', models.BooleanField(default=False)),
                ('experience', models.ManyToManyField(blank=True, to='scheduler.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('av', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=4)),
                ('time', models.CharField(blank=True, help_text='Format: <em>10AM</em>.', max_length=10)),
                ('tracks', models.IntegerField(default=3, help_text='Number of rooms available to us in this slot.')),
                ('previous_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_slot', to='scheduler.Timeslot', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='panel',
            name='final_panelists',
            field=models.ManyToManyField(blank=True, related_name='panels', to='scheduler.Panelist'),
        ),
        migrations.AddField(
            model_name='panel',
            name='interested_panelists',
            field=models.ManyToManyField(blank=True, related_name='interested', to='scheduler.Panelist'),
        ),
        migrations.AddField(
            model_name='panel',
            name='required_panelists',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='scheduler.Panelist'),
        ),
        migrations.AddField(
            model_name='panel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.Room'),
        ),
        migrations.AddField(
            model_name='panel',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='scheduler.Timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'time')},
        ),
    ]
