# Generated by Django 2.0 on 2018-12-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelist',
            name='person_of_color',
        ),
        migrations.AddField(
            model_name='panelist',
            name='email',
            field=models.CharField(default='none', max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelist',
            name='white',
            field=models.BooleanField(default=True),
        ),
    ]
