# Generated by Django 2.0 on 2018-12-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20181215_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='previous_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_slot', to='scheduler.Timeslot'),
        ),
    ]
