# Generated by Django 2.1.4 on 2018-12-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_panel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='interested_moderators',
            field=models.ManyToManyField(blank=True, related_name='interested_mod', to='scheduler.Panelist'),
        ),
        migrations.AddField(
            model_name='panel',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderating', to='scheduler.Panelist'),
        ),
    ]
