# Generated by Django 2.1.4 on 2018-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_add_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
