# Generated by Django 2.1.4 on 2018-12-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='roomsize',
            field=models.IntegerField(default=50, help_text='How many audience seats should the room have?'),
            preserve_default=False,
        ),
    ]
