# Generated by Django 2.1.4 on 2018-12-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20181218_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, choices=[('panel', 'panel'), ('reading', 'reading'), ('special', 'special')], max_length=10),
        ),
    ]
