# Generated by Django 2.1.4 on 2018-12-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20181219_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='locked',
            new_name='panelists_locked',
        ),
    ]
