# Generated by Django 2.1.4 on 2018-12-21 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20181220_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='scheduler.Conference'),
        ),
        migrations.AddField(
            model_name='panelist',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panelists', to='scheduler.Conference'),
        ),
        migrations.AddField(
            model_name='room',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='scheduler.Conference'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeslots', to='scheduler.Conference'),
        ),
    ]
