# Generated by Django 2.1.4 on 2018-12-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20181221_0054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'time', 'conference')},
        ),
    ]
