# Generated by Django 2.1.4 on 2018-12-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20181221_0201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panel',
            unique_together={('room', 'timeslot', 'conference')},
        ),
    ]
