# Generated by Django 2.1.4 on 2018-12-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_panel_unique_together_20181222_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='reading_slots',
            field=models.IntegerField(default=3, help_text='Number of readings available this slot.'),
        ),
    ]
