# Generated by Django 2.1.4 on 2018-12-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_timeslot_reading_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='reading_requested',
            field=models.BooleanField(default=False),
        ),
    ]
