# Generated by Django 2.1.4 on 2018-12-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_panelist_reading_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='av_required',
            field=models.BooleanField(default=False),
        ),
    ]
