# Generated by Django 2.2.4 on 2019-09-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_auto_20190930_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('slug', 'conference')},
        ),
    ]
