# Generated by Django 2.2.4 on 2019-09-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_migrate_pro_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='pro_track',
        ),
    ]
