# Generated by Django 2.2.4 on 2019-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_remove_panel_pro_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for conference planners.', null=True),
        ),
    ]
