# Generated by Django 2.2.4 on 2019-10-16 01:10

from django.db import migrations, models

def migrate_on_form_and_publish(apps, schema_editor):
    Panel = apps.get_model('scheduler', 'Panel')

    for panel in Panel.objects.all():
        panel.on_form = True
        panel.publish = True
        panel.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0027_panel_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='on_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panel',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='panel',
            name='roomsize',
            field=models.IntegerField(
                default=30, help_text='How many audience seats should the room have?'),
        ),

        migrations.RunPython(migrate_on_form_and_publish),
    ]
