# Generated by Django 2.2.4 on 2019-10-20 16:23

from django.db import migrations, models

def migrate_program_name(apps, schema_editor):
    Panelist = apps.get_model('scheduler', 'Panelist')

    for panelist in Panelist.objects.all():
        panelist.program_name = panelist.badge_name
        panelist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0028_auto_20191016_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='program_name',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.RunPython(migrate_program_name),
        migrations.AlterField(
            model_name='panelist',
            name='program_name',
            field=models.CharField(max_length=280),
        ),
    ]
