# Generated by Django 2.2.4 on 2019-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_panelist_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
