# Generated by Django 2.2.4 on 2019-11-11 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_auto_20191109_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='panel',
            constraint=models.CheckConstraint(check=models.Q(start_time__lte=django.db.models.expressions.F('end_time')), name='valid-time'),
        ),
        migrations.AddField(
            model_name='day',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Conference'),
        ),
    ]
