# Generated by Django 2.2.4 on 2019-11-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0031_auto_20191111_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='limit_concurrent',
            field=models.IntegerField(default=0, help_text='Limit how many panels can run at once (zero for no limit)'),
        ),
        migrations.AddField(
            model_name='track',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='scheduler.Conference'),
        ),
    ]
