# Generated by Django 2.2.4 on 2019-11-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0032_auto_20191111_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='schedule',
            field=models.BooleanField(default=True),
        ),
    ]
