# Generated by Django 2.2.4 on 2021-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0033_track_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='panelist_registration_open',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
